"""Widget schemas — the contract between agent and frontend.

This file is the source of truth. TypeScript types in lib/widgets.ts
must mirror these definitions. Change Pydantic first, mirror in TS in
the same commit.
"""

from __future__ import annotations

import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Common types
# ---------------------------------------------------------------------------

WidgetType = Literal[
    "query_plan",
    "results_table",
    "timeseries_chart",
    "log_tail",
    "summary_card",
    "confirmation",
]

WidgetPlacement = Literal["canvas", "inline"]

WidgetStatus = Literal[
    "draft",
    "submitted",
    "running",
    "complete",
    "error",
    "cancelled",
]


class WidgetAction(BaseModel):
    """Describes a user-actionable button on a widget."""

    label: str
    enabled: bool = True


# ---------------------------------------------------------------------------
# Base widget
# ---------------------------------------------------------------------------


class BaseWidget(BaseModel):
    """Common fields shared by all widget types."""

    id: str = Field(description="ULID, generated by the agent")
    type: WidgetType
    placement: WidgetPlacement = "canvas"
    status: WidgetStatus = "draft"
    title: str = ""
    created_at: str = Field(
        default_factory=lambda: datetime.datetime.now(datetime.UTC).isoformat()
    )
    created_by_run: str = ""
    error_message: str | None = None


# ---------------------------------------------------------------------------
# Widget types
# ---------------------------------------------------------------------------


class QueryPlanWidget(BaseWidget):
    """Editable Logs Insights query with approve/reject actions."""

    type: Literal["query_plan"] = "query_plan"
    query: str = ""
    log_groups: list[str] = Field(default_factory=list)
    available_log_groups: list[str] = Field(default_factory=list)
    start_time: str | None = None
    end_time: str | None = None
    actions: dict[str, WidgetAction] = Field(
        default_factory=lambda: {
            "approve": WidgetAction(label="Approve"),
            "reject": WidgetAction(label="Reject"),
        }
    )


class ResultsTableColumn(BaseModel):
    """Column definition for a results table."""

    key: str
    label: str


class ResultsTableWidget(BaseWidget):
    """Streaming table of query results."""

    type: Literal["results_table"] = "results_table"
    columns: list[ResultsTableColumn] = Field(default_factory=list)
    rows: list[dict[str, Any]] = Field(default_factory=list)


class TimeseriesPoint(BaseModel):
    """A single data point in a timeseries."""

    timestamp: str
    value: float


class TimeseriesSeries(BaseModel):
    """A named series of timestamped values."""

    name: str
    data: list[TimeseriesPoint] = Field(default_factory=list)


class TimeseriesChartWidget(BaseWidget):
    """Timeseries chart with one or more named series."""

    type: Literal["timeseries_chart"] = "timeseries_chart"
    series: list[TimeseriesSeries] = Field(default_factory=list)
    x_label: str = "Time"
    y_label: str = "Value"


class LogLine(BaseModel):
    """A single log line with severity."""

    timestamp: str
    message: str
    severity: Literal["debug", "info", "warn", "error"] = "info"


class LogTailWidget(BaseWidget):
    """Ring-buffered log lines with severity coloring."""

    type: Literal["log_tail"] = "log_tail"
    lines: list[LogLine] = Field(default_factory=list)
    max_lines: int = 200


class SummaryItem(BaseModel):
    """A key/value pair with optional trend indicator."""

    label: str
    value: str
    trend: Literal["up", "down", "flat", "none"] = "none"


class SummaryCardWidget(BaseWidget):
    """Key/value summary with optional trend indicators."""

    type: Literal["summary_card"] = "summary_card"
    items: list[SummaryItem] = Field(default_factory=list)


class ConfirmationWidget(BaseWidget):
    """Yes/no prompt with optional rejection reason."""

    type: Literal["confirmation"] = "confirmation"
    message: str = ""
    actions: dict[str, WidgetAction] = Field(
        default_factory=lambda: {
            "confirm": WidgetAction(label="Confirm"),
            "reject": WidgetAction(label="Reject"),
        }
    )
    rejection_reason: str | None = None


# ---------------------------------------------------------------------------
# Union type for serialization / deserialization
# ---------------------------------------------------------------------------

Widget = (
    QueryPlanWidget
    | ResultsTableWidget
    | TimeseriesChartWidget
    | LogTailWidget
    | SummaryCardWidget
    | ConfirmationWidget
)
