"""Pydantic models for scheduled tasks and run history."""

from __future__ import annotations

import datetime
from typing import Literal

from pydantic import BaseModel, Field

# Default timezone for cron schedules and displayed times.
# America/New_York observes EST/EDT depending on the date — the
# scheduler library handles DST transitions automatically.
DEFAULT_TIMEZONE = "America/New_York"


def _now_iso() -> str:
    """Return the current time as an ISO 8601 string in UTC."""
    return datetime.datetime.now(datetime.UTC).isoformat()


class ScheduledTask(BaseModel):
    """A user-defined task that runs the agent on a cron schedule."""

    id: str = Field(description="ULID generated by the agent")
    name: str
    prompt: str = Field(description="The user message sent to the agent on each run")
    cron: str = Field(description="Cron expression (5-field, e.g. '0 9 * * 1-5')")
    timezone: str = DEFAULT_TIMEZONE
    enabled: bool = True
    created_at: str = Field(default_factory=_now_iso)
    last_run_at: str | None = None
    last_run_status: Literal["success", "failed"] | None = None
    last_run_id: str | None = None


class TaskRun(BaseModel):
    """A single execution of a scheduled task."""

    id: str = Field(description="ULID")
    task_id: str
    started_at: str = Field(default_factory=_now_iso)
    completed_at: str | None = None
    status: Literal["running", "success", "failed"] = "running"
    response: str | None = Field(default=None, description="Final assistant text")
    error: str | None = None
    trigger: Literal["scheduled", "manual"] = "scheduled"


# ---------------------------------------------------------------------------
# Schedule presets — friendly options for the UI dropdown
# ---------------------------------------------------------------------------

SCHEDULE_PRESETS: list[dict[str, str]] = [
    {"label": "Every 5 minutes", "cron": "*/5 * * * *"},
    {"label": "Every 15 minutes", "cron": "*/15 * * * *"},
    {"label": "Every hour", "cron": "0 * * * *"},
    {"label": "Every 6 hours", "cron": "0 */6 * * *"},
    {"label": "Daily at 9am EST", "cron": "0 9 * * *"},
    {"label": "Weekdays at 9am EST", "cron": "0 9 * * 1-5"},
    {"label": "Weekly Monday 9am EST", "cron": "0 9 * * 1"},
]


# ---------------------------------------------------------------------------
# Request bodies for REST endpoints
# ---------------------------------------------------------------------------


class CreateTaskRequest(BaseModel):
    name: str
    prompt: str
    cron: str
    timezone: str = DEFAULT_TIMEZONE
    enabled: bool = True


class UpdateTaskRequest(BaseModel):
    name: str | None = None
    prompt: str | None = None
    cron: str | None = None
    enabled: bool | None = None
